sens_t sens[44] = {
  { 23,  1, 24,  1, "PF(13)" },
  { 26,  1, 27,  1, "PF(14)" },
  { 29,  1, 30,  1, "PF(15)" },
  { 32,  1, 33,  1, "PF(16)" },
  { 35,  1, 36,  1, "PF(17)" },
  { 38,  1, 39,  1, "PF(18)" },
  { 41,  1, 42,  1, "PF(19)" },
  { 44,  1, 45,  1, "PF(20)" },
  { 47,  1, 48,  1, "PF(21)" },
  { 50,  1, 51,  1, "PF(22)" },
  { 53,  1, 54,  1, "PF(23)" },
  { 56,  1, 57,  1, "PF(24)" },
  {  3,  2,  8,  3, "PA(1)" },
  { 10,  2, 15,  3, "PA(2)" },
  { 63,  2, 68,  3, "Home" },
  { 23,  3, 24,  3, "PF(1)" },
  { 26,  3, 27,  3, "PF(2)" },
  { 29,  3, 30,  3, "PF(3)" },
  { 32,  3, 33,  3, "PF(4)" },
  { 35,  3, 36,  3, "PF(5)" },
  { 38,  3, 39,  3, "PF(6)" },
  { 41,  3, 42,  3, "PF(7)" },
  { 44,  3, 45,  3, "PF(8)" },
  { 47,  3, 48,  3, "PF(9)" },
  { 50,  3, 51,  3, "PF(10)" },
  { 53,  3, 54,  3, "PF(11)" },
  { 56,  3, 57,  3, "PF(12)" },
  {  3,  5,  8,  6, "Attn" },
  { 10,  5, 15,  6, "PA(3)" },
  { 63,  5, 68,  6, "CursorSelect" },
  { 70,  5, 75,  6, "Compose" },
  { 23,  7, 29,  7, "Tab" },
  { 51,  7, 57,  7, "BackTab" },
  {  3,  8,  8,  9, "EraseEOF" },
  { 10,  8, 15,  9, "EraseInput" },
  { 63,  8, 68,  9, "Insert" },
  { 70,  8, 75,  9, "Delete" },
  { 51,  9, 57, 10, "Newline" },
  {  3, 11,  8, 12, "SysReq" },
  { 10, 11, 15, 12, "Clear" },
  { 63, 11, 68, 12, "Dup" },
  { 70, 11, 75, 12, "FieldMark" },
  { 23, 13, 29, 13, "Reset" },
  { 51, 13, 57, 13, "Enter" },
};
keypad_desc_t keypad_desc[16][80] = {
{ /* row 0 */
  {   0,   0, NULL },
  { ' ', 's', NULL },
  { ' ', 's', NULL },
  { ' ', 's', NULL },
  { ' ', 's', NULL },
  { ' ', 's', NULL },
  { ' ', 's', NULL },
  { ' ', 's', NULL },
  { ' ', 's', NULL },
  { ' ', 's', NULL },
  { ' ', 's', NULL },
  { ' ', 's', NULL },
  { ' ', 's', NULL },
  { ' ', 's', NULL },
  { ' ', 's', NULL },
  { ' ', 's', NULL },
  { ' ', 's', NULL },
  { ' ', 's', NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  { ' ', 's', NULL },
  { ' ', 'l', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'w', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'w', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'w', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'w', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'w', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'w', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'w', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'w', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'w', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'w', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'w', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'k', NULL },
  { ' ', 's', NULL },
  {   0,   0, NULL },
  { ' ', 's', NULL },
  { ' ', 's', NULL },
  { ' ', 's', NULL },
  { ' ', 's', NULL },
  { ' ', 's', NULL },
  { ' ', 's', NULL },
  { ' ', 's', NULL },
  { ' ', 's', NULL },
  { ' ', 's', NULL },
  { ' ', 's', NULL },
  { ' ', 's', NULL },
  { ' ', 's', NULL },
  { ' ', 's', NULL },
  { ' ', 's', NULL },
  { ' ', 's', NULL },
  { ' ', 's', NULL },
  { ' ', 's', NULL },
},
{ /* row 1 */
  {   0,   0, NULL },
  { ' ', 's', NULL },
  { ' ', 'l', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'w', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'k', NULL },
  { ' ', 's', NULL },
  { ' ', 's', NULL },
  { 'P', ' ', NULL },
  { 'F', ' ', NULL },
  { '-', 's', NULL },
  { ' ', 'x', NULL },
  { '1', ' ', &sens[0] },
  { '3', ' ', &sens[0] },
  { ' ', 'x', NULL },
  { '1', ' ', &sens[1] },
  { '4', ' ', &sens[1] },
  { ' ', 'x', NULL },
  { '1', ' ', &sens[2] },
  { '5', ' ', &sens[2] },
  { ' ', 'x', NULL },
  { '1', ' ', &sens[3] },
  { '6', ' ', &sens[3] },
  { ' ', 'x', NULL },
  { '1', ' ', &sens[4] },
  { '7', ' ', &sens[4] },
  { ' ', 'x', NULL },
  { '1', ' ', &sens[5] },
  { '8', ' ', &sens[5] },
  { ' ', 'x', NULL },
  { '1', ' ', &sens[6] },
  { '9', ' ', &sens[6] },
  { ' ', 'x', NULL },
  { '2', ' ', &sens[7] },
  { '0', ' ', &sens[7] },
  { ' ', 'x', NULL },
  { '2', ' ', &sens[8] },
  { '1', ' ', &sens[8] },
  { ' ', 'x', NULL },
  { '2', ' ', &sens[9] },
  { '2', ' ', &sens[9] },
  { ' ', 'x', NULL },
  { '2', ' ', &sens[10] },
  { '3', ' ', &sens[10] },
  { ' ', 'x', NULL },
  { '2', ' ', &sens[11] },
  { '4', ' ', &sens[11] },
  { ' ', 'x', NULL },
  { ' ', 's', NULL },
  {   0,   0, NULL },
  { ' ', 's', NULL },
  { ' ', 'l', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'w', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'k', NULL },
  { ' ', 's', NULL },
},
{ /* row 2 */
  {   0,   0, NULL },
  { ' ', 's', NULL },
  { ' ', 'x', NULL },
  { ' ', ' ', &sens[12] },
  { 'P', ' ', &sens[12] },
  { 'A', ' ', &sens[12] },
  { '1', ' ', &sens[12] },
  { ' ', ' ', &sens[12] },
  { ' ', ' ', &sens[12] },
  { ' ', 'x', NULL },
  { ' ', ' ', &sens[13] },
  { 'P', ' ', &sens[13] },
  { 'A', ' ', &sens[13] },
  { '2', ' ', &sens[13] },
  { ' ', ' ', &sens[13] },
  { ' ', ' ', &sens[13] },
  { ' ', 'x', NULL },
  { ' ', 's', NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  { ' ', 's', NULL },
  { ' ', 't', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'n', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'n', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'n', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'n', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'n', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'n', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'n', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'n', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'n', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'n', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'n', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'u', NULL },
  { ' ', 's', NULL },
  {   0,   0, NULL },
  { ' ', 's', NULL },
  { ' ', 'x', NULL },
  { ' ', ' ', &sens[14] },
  { 'H', ' ', &sens[14] },
  { 'o', ' ', &sens[14] },
  { 'm', ' ', &sens[14] },
  { 'e', ' ', &sens[14] },
  { ' ', ' ', &sens[14] },
  { ' ', 'x', NULL },
  { ' ', 's', NULL },
  { ' ', 's', NULL },
  { ' ', 's', NULL },
  { ' ', 's', NULL },
  { ' ', 's', NULL },
  { ' ', 's', NULL },
  { ' ', 'x', NULL },
  { ' ', 's', NULL },
},
{ /* row 3 */
  {   0,   0, NULL },
  { ' ', 's', NULL },
  { ' ', 'x', NULL },
  { ' ', ' ', &sens[12] },
  { ' ', ' ', &sens[12] },
  { ' ', ' ', &sens[12] },
  { ' ', ' ', &sens[12] },
  { ' ', ' ', &sens[12] },
  { ' ', ' ', &sens[12] },
  { ' ', 'x', NULL },
  { ' ', ' ', &sens[13] },
  { ' ', ' ', &sens[13] },
  { ' ', ' ', &sens[13] },
  { ' ', ' ', &sens[13] },
  { ' ', ' ', &sens[13] },
  { ' ', ' ', &sens[13] },
  { ' ', 'x', NULL },
  { ' ', 's', NULL },
  { ' ', 's', NULL },
  { 'P', ' ', NULL },
  { 'F', ' ', NULL },
  { '-', 's', NULL },
  { ' ', 'x', NULL },
  { ' ', ' ', &sens[15] },
  { '1', ' ', &sens[15] },
  { ' ', 'x', NULL },
  { ' ', ' ', &sens[16] },
  { '2', ' ', &sens[16] },
  { ' ', 'x', NULL },
  { ' ', ' ', &sens[17] },
  { '3', ' ', &sens[17] },
  { ' ', 'x', NULL },
  { ' ', ' ', &sens[18] },
  { '4', ' ', &sens[18] },
  { ' ', 'x', NULL },
  { ' ', ' ', &sens[19] },
  { '5', ' ', &sens[19] },
  { ' ', 'x', NULL },
  { ' ', ' ', &sens[20] },
  { '6', ' ', &sens[20] },
  { ' ', 'x', NULL },
  { ' ', ' ', &sens[21] },
  { '7', ' ', &sens[21] },
  { ' ', 'x', NULL },
  { ' ', ' ', &sens[22] },
  { '8', ' ', &sens[22] },
  { ' ', 'x', NULL },
  { ' ', ' ', &sens[23] },
  { '9', ' ', &sens[23] },
  { ' ', 'x', NULL },
  { '1', ' ', &sens[24] },
  { '0', ' ', &sens[24] },
  { ' ', 'x', NULL },
  { '1', ' ', &sens[25] },
  { '1', ' ', &sens[25] },
  { ' ', 'x', NULL },
  { '1', ' ', &sens[26] },
  { '2', ' ', &sens[26] },
  { ' ', 'x', NULL },
  { ' ', 's', NULL },
  {   0,   0, NULL },
  { ' ', 's', NULL },
  { ' ', 'x', NULL },
  { ' ', ' ', &sens[14] },
  { ' ', ' ', &sens[14] },
  { ' ', ' ', &sens[14] },
  { ' ', ' ', &sens[14] },
  { ' ', ' ', &sens[14] },
  { ' ', ' ', &sens[14] },
  { ' ', 'x', NULL },
  { ' ', 's', NULL },
  { ' ', 's', NULL },
  { ' ', 's', NULL },
  { ' ', 's', NULL },
  { ' ', 's', NULL },
  { ' ', 's', NULL },
  { ' ', 'x', NULL },
  { ' ', 's', NULL },
},
{ /* row 4 */
  {   0,   0, NULL },
  { ' ', 's', NULL },
  { ' ', 't', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'n', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'u', NULL },
  { ' ', 's', NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  { ' ', 's', NULL },
  { ' ', 'm', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'v', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'v', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'v', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'v', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'v', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'v', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'v', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'v', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'v', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'v', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'v', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'j', NULL },
  { ' ', 's', NULL },
  {   0,   0, NULL },
  { ' ', 's', NULL },
  { ' ', 't', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'n', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'u', NULL },
  { ' ', 's', NULL },
},
{ /* row 5 */
  {   0,   0, NULL },
  { ' ', 's', NULL },
  { ' ', 'x', NULL },
  { ' ', ' ', &sens[27] },
  { 'A', ' ', &sens[27] },
  { 't', ' ', &sens[27] },
  { 't', ' ', &sens[27] },
  { 'n', ' ', &sens[27] },
  { ' ', ' ', &sens[27] },
  { ' ', 'x', NULL },
  { ' ', ' ', &sens[28] },
  { 'P', ' ', &sens[28] },
  { 'A', ' ', &sens[28] },
  { '3', ' ', &sens[28] },
  { ' ', ' ', &sens[28] },
  { ' ', ' ', &sens[28] },
  { ' ', 'x', NULL },
  { ' ', 's', NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  { ' ', 's', NULL },
  { ' ', 's', NULL },
  { ' ', 's', NULL },
  { ' ', 's', NULL },
  { ' ', 's', NULL },
  { ' ', 's', NULL },
  { ' ', 's', NULL },
  { ' ', 's', NULL },
  { ' ', 's', NULL },
  { ' ', 's', NULL },
  { ' ', 's', NULL },
  { ' ', 's', NULL },
  { ' ', 's', NULL },
  { ' ', 's', NULL },
  { ' ', 's', NULL },
  { ' ', 's', NULL },
  { ' ', 's', NULL },
  { ' ', 's', NULL },
  { ' ', 's', NULL },
  { ' ', 's', NULL },
  { ' ', 's', NULL },
  { ' ', 's', NULL },
  { ' ', 's', NULL },
  { ' ', 's', NULL },
  { ' ', 's', NULL },
  { ' ', 's', NULL },
  { ' ', 's', NULL },
  { ' ', 's', NULL },
  { ' ', 's', NULL },
  { ' ', 's', NULL },
  { ' ', 's', NULL },
  { ' ', 's', NULL },
  { ' ', 's', NULL },
  { ' ', 's', NULL },
  { ' ', 's', NULL },
  { ' ', 's', NULL },
  { ' ', 's', NULL },
  { ' ', 's', NULL },
  { ' ', 's', NULL },
  {   0,   0, NULL },
  { ' ', 's', NULL },
  { ' ', 'x', NULL },
  { 'C', ' ', &sens[29] },
  { 'u', ' ', &sens[29] },
  { 'r', ' ', &sens[29] },
  { 's', ' ', &sens[29] },
  { 'o', ' ', &sens[29] },
  { 'r', ' ', &sens[29] },
  { ' ', 'x', NULL },
  { 'C', ' ', &sens[30] },
  { 'm', ' ', &sens[30] },
  { 'p', ' ', &sens[30] },
  { 'o', ' ', &sens[30] },
  { 's', ' ', &sens[30] },
  { 'e', ' ', &sens[30] },
  { ' ', 'x', NULL },
  { ' ', 's', NULL },
},
{ /* row 6 */
  {   0,   0, NULL },
  { ' ', 's', NULL },
  { ' ', 'x', NULL },
  { ' ', ' ', &sens[27] },
  { ' ', ' ', &sens[27] },
  { ' ', ' ', &sens[27] },
  { ' ', ' ', &sens[27] },
  { ' ', ' ', &sens[27] },
  { ' ', ' ', &sens[27] },
  { ' ', 'x', NULL },
  { ' ', ' ', &sens[28] },
  { ' ', ' ', &sens[28] },
  { ' ', ' ', &sens[28] },
  { ' ', ' ', &sens[28] },
  { ' ', ' ', &sens[28] },
  { ' ', ' ', &sens[28] },
  { ' ', 'x', NULL },
  { ' ', 's', NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  { ' ', 's', NULL },
  { ' ', 'l', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'k', NULL },
  { ' ', 's', NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  { ' ', 's', NULL },
  { ' ', 'l', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'k', NULL },
  { ' ', 's', NULL },
  {   0,   0, NULL },
  { ' ', 's', NULL },
  { ' ', 'x', NULL },
  { 'S', ' ', &sens[29] },
  { 'e', ' ', &sens[29] },
  { 'l', ' ', &sens[29] },
  { 'e', ' ', &sens[29] },
  { 'c', ' ', &sens[29] },
  { 't', ' ', &sens[29] },
  { ' ', 'x', NULL },
  { ' ', ' ', &sens[30] },
  { ' ', ' ', &sens[30] },
  { ' ', ' ', &sens[30] },
  { ' ', ' ', &sens[30] },
  { ' ', ' ', &sens[30] },
  { ' ', ' ', &sens[30] },
  { ' ', 'x', NULL },
  { ' ', 's', NULL },
},
{ /* row 7 */
  {   0,   0, NULL },
  { ' ', 's', NULL },
  { ' ', 't', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'n', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'u', NULL },
  { ' ', 's', NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  { ' ', 's', NULL },
  { ' ', 'x', NULL },
  { ' ', ' ', &sens[31] },
  { ' ', 'q', &sens[31] },
  { ' ', 'q', &sens[31] },
  { '>', ' ', &sens[31] },
  { ' ', 'x', &sens[31] },
  { ' ', ' ', &sens[31] },
  { ' ', ' ', &sens[31] },
  { ' ', 'x', NULL },
  { ' ', 's', NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  { ' ', 's', NULL },
  { ' ', 'x', NULL },
  { ' ', ' ', &sens[32] },
  { ' ', 'x', &sens[32] },
  { '<', ' ', &sens[32] },
  { ' ', 'q', &sens[32] },
  { ' ', 'q', &sens[32] },
  { ' ', ' ', &sens[32] },
  { ' ', ' ', &sens[32] },
  { ' ', 'x', NULL },
  { ' ', 's', NULL },
  {   0,   0, NULL },
  { ' ', 's', NULL },
  { ' ', 't', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'n', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'u', NULL },
  { ' ', 's', NULL },
},
{ /* row 8 */
  {   0,   0, NULL },
  { ' ', 's', NULL },
  { ' ', 'x', NULL },
  { 'E', ' ', &sens[33] },
  { 'r', ' ', &sens[33] },
  { 'a', ' ', &sens[33] },
  { 's', ' ', &sens[33] },
  { 'e', ' ', &sens[33] },
  { ' ', ' ', &sens[33] },
  { ' ', 'x', NULL },
  { 'E', ' ', &sens[34] },
  { 'r', ' ', &sens[34] },
  { 'a', ' ', &sens[34] },
  { 's', ' ', &sens[34] },
  { 'e', ' ', &sens[34] },
  { ' ', ' ', &sens[34] },
  { ' ', 'x', NULL },
  { ' ', 's', NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  { ' ', 's', NULL },
  { ' ', 'm', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'j', NULL },
  { ' ', 's', NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  { ' ', 's', NULL },
  { ' ', 't', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'u', NULL },
  { ' ', 's', NULL },
  {   0,   0, NULL },
  { ' ', 's', NULL },
  { ' ', 'x', NULL },
  { 'I', ' ', &sens[35] },
  { 'n', ' ', &sens[35] },
  { 's', ' ', &sens[35] },
  { 'e', ' ', &sens[35] },
  { 'r', ' ', &sens[35] },
  { 't', ' ', &sens[35] },
  { ' ', 'x', NULL },
  { 'D', ' ', &sens[36] },
  { 'e', ' ', &sens[36] },
  { 'l', ' ', &sens[36] },
  { 'e', ' ', &sens[36] },
  { 't', ' ', &sens[36] },
  { 'e', ' ', &sens[36] },
  { ' ', 'x', NULL },
  { ' ', 's', NULL },
},
{ /* row 9 */
  {   0,   0, NULL },
  { ' ', 's', NULL },
  { ' ', 'x', NULL },
  { ' ', ' ', &sens[33] },
  { 'E', ' ', &sens[33] },
  { 'O', ' ', &sens[33] },
  { 'F', ' ', &sens[33] },
  { ' ', ' ', &sens[33] },
  { ' ', ' ', &sens[33] },
  { ' ', 'x', NULL },
  { 'I', ' ', &sens[34] },
  { 'n', ' ', &sens[34] },
  { 'p', ' ', &sens[34] },
  { 'u', ' ', &sens[34] },
  { 't', ' ', &sens[34] },
  { ' ', ' ', &sens[34] },
  { ' ', 'x', NULL },
  { ' ', 's', NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  { ' ', 's', NULL },
  { ' ', 'x', NULL },
  { ' ', ' ', &sens[37] },
  { ' ', ' ', &sens[37] },
  { ' ', ' ', &sens[37] },
  { ' ', ' ', &sens[37] },
  { ' ', 'x', &sens[37] },
  { ' ', ' ', &sens[37] },
  { ' ', ' ', &sens[37] },
  { ' ', 'x', NULL },
  { ' ', 's', NULL },
  {   0,   0, NULL },
  { ' ', 's', NULL },
  { ' ', 'x', NULL },
  { ' ', ' ', &sens[35] },
  { ' ', ' ', &sens[35] },
  { ' ', ' ', &sens[35] },
  { ' ', ' ', &sens[35] },
  { ' ', ' ', &sens[35] },
  { ' ', ' ', &sens[35] },
  { ' ', 'x', NULL },
  { ' ', ' ', &sens[36] },
  { ' ', ' ', &sens[36] },
  { ' ', ' ', &sens[36] },
  { ' ', ' ', &sens[36] },
  { ' ', ' ', &sens[36] },
  { ' ', ' ', &sens[36] },
  { ' ', 'x', NULL },
  { ' ', 's', NULL },
},
{ /* row 10 */
  {   0,   0, NULL },
  { ' ', 's', NULL },
  { ' ', 't', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'n', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'u', NULL },
  { ' ', 's', NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  { ' ', 's', NULL },
  { ' ', 'x', NULL },
  { ' ', ' ', &sens[37] },
  { ' ', ' ', &sens[37] },
  { '<', ' ', &sens[37] },
  { ' ', 'q', &sens[37] },
  { ' ', 'j', &sens[37] },
  { ' ', ' ', &sens[37] },
  { ' ', ' ', &sens[37] },
  { ' ', 'x', NULL },
  { ' ', 's', NULL },
  {   0,   0, NULL },
  { ' ', 's', NULL },
  { ' ', 't', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'n', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'u', NULL },
  { ' ', 's', NULL },
},
{ /* row 11 */
  {   0,   0, NULL },
  { ' ', 's', NULL },
  { ' ', 'x', NULL },
  { ' ', ' ', &sens[38] },
  { 'S', ' ', &sens[38] },
  { 'y', ' ', &sens[38] },
  { 's', ' ', &sens[38] },
  { ' ', ' ', &sens[38] },
  { ' ', ' ', &sens[38] },
  { ' ', 'x', NULL },
  { 'C', ' ', &sens[39] },
  { 'l', ' ', &sens[39] },
  { 'e', ' ', &sens[39] },
  { 'a', ' ', &sens[39] },
  { 'r', ' ', &sens[39] },
  { ' ', ' ', &sens[39] },
  { ' ', 'x', NULL },
  { ' ', 's', NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  { ' ', 's', NULL },
  { ' ', 's', NULL },
  { ' ', 's', NULL },
  { ' ', 's', NULL },
  { ' ', 's', NULL },
  { ' ', 's', NULL },
  { ' ', 's', NULL },
  { ' ', 's', NULL },
  { ' ', 's', NULL },
  { ' ', 's', NULL },
  { ' ', 's', NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  { ' ', 's', NULL },
  { ' ', 'm', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'j', NULL },
  { ' ', 's', NULL },
  {   0,   0, NULL },
  { ' ', 's', NULL },
  { ' ', 'x', NULL },
  { ' ', ' ', &sens[40] },
  { 'D', ' ', &sens[40] },
  { 'u', ' ', &sens[40] },
  { 'p', ' ', &sens[40] },
  { ' ', ' ', &sens[40] },
  { ' ', ' ', &sens[40] },
  { ' ', 'x', NULL },
  { 'F', ' ', &sens[41] },
  { 'i', ' ', &sens[41] },
  { 'e', ' ', &sens[41] },
  { 'l', ' ', &sens[41] },
  { 'd', ' ', &sens[41] },
  { ' ', ' ', &sens[41] },
  { ' ', 'x', NULL },
  { ' ', 's', NULL },
},
{ /* row 12 */
  {   0,   0, NULL },
  { ' ', 's', NULL },
  { ' ', 'x', NULL },
  { ' ', ' ', &sens[38] },
  { 'R', ' ', &sens[38] },
  { 'e', ' ', &sens[38] },
  { 'q', ' ', &sens[38] },
  { ' ', ' ', &sens[38] },
  { ' ', ' ', &sens[38] },
  { ' ', 'x', NULL },
  { ' ', ' ', &sens[39] },
  { ' ', ' ', &sens[39] },
  { ' ', ' ', &sens[39] },
  { ' ', ' ', &sens[39] },
  { ' ', ' ', &sens[39] },
  { ' ', ' ', &sens[39] },
  { ' ', 'x', NULL },
  { ' ', 's', NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  { ' ', 's', NULL },
  { ' ', 'l', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'k', NULL },
  { ' ', 's', NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  { ' ', 's', NULL },
  { ' ', 'l', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'k', NULL },
  { ' ', 's', NULL },
  {   0,   0, NULL },
  { ' ', 's', NULL },
  { ' ', 'x', NULL },
  { ' ', ' ', &sens[40] },
  { ' ', ' ', &sens[40] },
  { ' ', ' ', &sens[40] },
  { ' ', ' ', &sens[40] },
  { ' ', ' ', &sens[40] },
  { ' ', ' ', &sens[40] },
  { ' ', 'x', NULL },
  { ' ', ' ', &sens[41] },
  { 'M', ' ', &sens[41] },
  { 'a', ' ', &sens[41] },
  { 'r', ' ', &sens[41] },
  { 'k', ' ', &sens[41] },
  { ' ', ' ', &sens[41] },
  { ' ', 'x', NULL },
  { ' ', 's', NULL },
},
{ /* row 13 */
  {   0,   0, NULL },
  { ' ', 's', NULL },
  { ' ', 'm', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'v', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'j', NULL },
  { ' ', 's', NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  { ' ', 's', NULL },
  { ' ', 'x', NULL },
  { ' ', ' ', &sens[42] },
  { 'R', ' ', &sens[42] },
  { 'e', ' ', &sens[42] },
  { 's', ' ', &sens[42] },
  { 'e', ' ', &sens[42] },
  { 't', ' ', &sens[42] },
  { ' ', ' ', &sens[42] },
  { ' ', 'x', NULL },
  { ' ', 's', NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  { ' ', 's', NULL },
  { ' ', 'x', NULL },
  { ' ', ' ', &sens[43] },
  { 'E', ' ', &sens[43] },
  { 'n', ' ', &sens[43] },
  { 't', ' ', &sens[43] },
  { 'e', ' ', &sens[43] },
  { 'r', ' ', &sens[43] },
  { ' ', ' ', &sens[43] },
  { ' ', 'x', NULL },
  { ' ', 's', NULL },
  {   0,   0, NULL },
  { ' ', 's', NULL },
  { ' ', 'm', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'v', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'j', NULL },
  { ' ', 's', NULL },
},
{ /* row 14 */
  {   0,   0, NULL },
  { ' ', 's', NULL },
  { ' ', 's', NULL },
  { ' ', 's', NULL },
  { ' ', 's', NULL },
  { ' ', 's', NULL },
  { ' ', 's', NULL },
  { ' ', 's', NULL },
  { ' ', 's', NULL },
  { ' ', 's', NULL },
  { ' ', 's', NULL },
  { ' ', 's', NULL },
  { ' ', 's', NULL },
  { ' ', 's', NULL },
  { ' ', 's', NULL },
  { ' ', 's', NULL },
  { ' ', 's', NULL },
  { ' ', 's', NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  { ' ', 's', NULL },
  { ' ', 'm', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'j', NULL },
  { ' ', 's', NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  { ' ', 's', NULL },
  { ' ', 'm', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'q', NULL },
  { ' ', 'j', NULL },
  { ' ', 's', NULL },
  {   0,   0, NULL },
  { ' ', 's', NULL },
  { ' ', 's', NULL },
  { ' ', 's', NULL },
  { ' ', 's', NULL },
  { ' ', 's', NULL },
  { ' ', 's', NULL },
  { ' ', 's', NULL },
  { ' ', 's', NULL },
  { ' ', 's', NULL },
  { ' ', 's', NULL },
  { ' ', 's', NULL },
  { ' ', 's', NULL },
  { ' ', 's', NULL },
  { ' ', 's', NULL },
  { ' ', 's', NULL },
  { ' ', 's', NULL },
  { ' ', 's', NULL },
},
{ /* row 15 */
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  { ' ', 's', NULL },
  { ' ', 's', NULL },
  { ' ', 's', NULL },
  { ' ', 's', NULL },
  { ' ', 's', NULL },
  { ' ', 's', NULL },
  { ' ', 's', NULL },
  { ' ', 's', NULL },
  { ' ', 's', NULL },
  { ' ', 's', NULL },
  { ' ', 's', NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  {   0,   0, NULL },
  { ' ', 's', NULL },
  { ' ', 's', NULL },
  { ' ', 's', NULL },
  { ' ', 's', NULL },
  { ' ', 's', NULL },
  { ' ', 's', NULL },
  { ' ', 's', NULL },
  { ' ', 's', NULL },
  { ' ', 's', NULL },
  { ' ', 's', NULL },
  { ' ', 's', NULL },
} };
